#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # colorscheme = "gruvbox"
    colorscheme = "molokai"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true #false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil" 
    statusline_iseparator = "arrow"  #"arrow" "bar"
    buffer_index_type = 1
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true #false
    
  	# =====>>> custom  =============================================
	  guifont = "monaco:h10"
	  filemanager = "nerdtree"
    autocomplete_method = "deoplte"	# ycm
    # bootstrap_before = "myspacevim#init"
    bootstrap_before = "myspacevim#before"
    bootstrap_after= "myspacevim#after"
    statusline_right_sections = ['fileformat', 'cursorpos', 'percentage', 'add_author']
    # autocomplete_method = "ycm"
    # guifont = "Inconsolata_NF:h10"
	  # vimcompatible = true
	

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

# =====>>> custom  ================================================
# [[layers]]
  # name = "dylayer"

[[custom_plugins]] 
  # repo = "https://gitee.com/daotoyi/VimPlugin-molokai"
  repo = "tomasr/molokai"
  merged = false

[[custom_plugins]] 
  repo = "vim-scripts/OmniCppComplete"
  merged = false

[[custom_plugins]] 
  repo = "jceb/vim-orgmode"
  merged = false
[[custom_plugins]] 
  repo = "mattn/calendar-vim"
  merged = false
[[custom_plugins]] 
  repo = "tpope/vim-speeddating"
  merged = false

# --- layers ---
[[layers]]
  name = "incsearch"
[[layers]]
  name = "denite"

[[layers]]
  # name = "tags" " if set tags, will create big tags ~/.cache/SpaceVim/C_User_xxxx.
  name = "gtags"

[[layers]]
  name = "tmux"
  tmux_navigator_modifier = "alt"

  
# --- C/C++/Python IDE ---
[[layers]]
    name = 'lang#c'
    enable_clang_syntax_highlight = true
	[layer.clang_std]
    cpp = "c11"
	
[[layers]]
  name = "lang#python"
  
[[layers]]
   name = "debug"
